#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/fanbus_music_2.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/minim-spi.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar" fanbus_music_2
